Polished ajax project
FrankBishop/ajax-project pull request #17
Opened 2021-03-03 18:59 UTC by FrankBishop

![Screenshot (255)](https://user-images.githubusercontent.com/75149451/109857312-68d3d980-7c0f-11eb-9383-fe2d7c72f6e2.png)
![Screenshot (256)](https://user-images.githubusercontent.com/75149451/109857319-6a9d9d00-7c0f-11eb-9ad4-1083e5c248ea.png)
![Screenshot (257)](https://user-images.githubusercontent.com/75149451/109857331-6c676080-7c0f-11eb-8702-205736b52ea0.png)
![Screenshot (258)](https://user-images.githubusercontent.com/75149451/109857338-6d988d80-7c0f-11eb-8e60-e8e90a105ced.png)
![Screenshot (259)](https://user-images.githubusercontent.com/75149451/109857347-70937e00-7c0f-11eb-8141-88ede83b509c.png)
![Screenshot (260)](https://user-images.githubusercontent.com/75149451/109857356-72f5d800-7c0f-11eb-990d-4bf99a944b42.png)
![Screenshot (261)](https://user-images.githubusercontent.com/75149451/109857366-75583200-7c0f-11eb-93e5-211603137d8b.png)
![Screenshot (262)](https://user-images.githubusercontent.com/75149451/109857375-7721f580-7c0f-11eb-9c5f-ad20be7668d8.png)
![Screenshot (263)](https://user-images.githubusercontent.com/75149451/109857380-79844f80-7c0f-11eb-99db-57d94023f14d.png)
![Screenshot (264)](https://user-images.githubusercontent.com/75149451/109857388-7be6a980-7c0f-11eb-8f58-6b9a5c154ae5.png)
![Screenshot (265)](https://user-images.githubusercontent.com/75149451/109857397-7d17d680-7c0f-11eb-9df7-88fd1eae1963.png)
![Screenshot (266)](https://user-images.githubusercontent.com/75149451/109857403-7ee19a00-7c0f-11eb-8efa-23cc944f4298.png)

2021-03-03 20:58 UTC, FrankBishop commented
![Screenshot (271)](https://user-images.githubusercontent.com/75149451/109871449-10f19e80-7c20-11eb-9ee8-b95acb99383a.png)
![Screenshot (272)](https://user-images.githubusercontent.com/75149451/109871450-10f19e80-7c20-11eb-9038-38164bf14586.png)
![Screenshot (273)](https://user-images.githubusercontent.com/75149451/109871454-1353f880-7c20-11eb-8896-dc7916eb413a.png)
![Screenshot (274)](https://user-images.githubusercontent.com/75149451/109871463-14852580-7c20-11eb-83f1-47dcd3d6a1de.png)
![Screenshot (275)](https://user-images.githubusercontent.com/75149451/109871475-16e77f80-7c20-11eb-9b8b-2776c862816e.png)
![Screenshot (276)](https://user-images.githubusercontent.com/75149451/109871487-18b14300-7c20-11eb-8e79-314be95ee591.png)
![Screenshot (277)](https://user-images.githubusercontent.com/75149451/109871493-1a7b0680-7c20-11eb-8d98-2d2959fee47d.png)
![Screenshot (278)](https://user-images.githubusercontent.com/75149451/109871506-1c44ca00-7c20-11eb-9721-b69645f57a4b.png)

2021-03-03 23:08 UTC, codingcodymiller requested changes

2021-03-03 23:08 UTC, codingcodymiller commented on css/layout.css
> +  }
make sure your code indentation remains consistent in your media queries. The closing curly brace for each rule should be at the same indentation as the selector, and every property should be indented by one from those.

2021-03-04 18:51 UTC, codingcodymiller approved these changes

2021-03-04 18:52 UTC, merged